from __future__ import annotations

# Shared football/domain vocabularies used across enterprise modules.
# PLAYER_DATA_LEAGUES and PLAYER_DATA_TEAMS were generated from DISTINCT player_data metadata on 2026-07-20.

ROLE_SHORT_TO_LONG = {
    "GK": "Goalkeeper",
    "LWB": "Left Wing Back",
    "LB": "Left Back",
    "LCB": "Left Center Back",
    "CB": "Center Back",
    "RCB": "Right Center Back",
    "RB": "Right Back",
    "RWB": "Right Wing Back",
    "LM": "Left Midfield",
    "LDM": "Left Defensive Midfield",
    "LCM": "Left Center Midfield",
    "LAM": "Left Attacking Midfield",
    "CM": "Center Midfield",
    "CAM": "Center Attacking Midfield",
    "CDM": "Center Defensive Midfield",
    "RDM": "Right Defensive Midfield",
    "RCM": "Right Center Midfield",
    "RAM": "Right Attacking Midfield",
    "RM": "Right Midfield",
    "CF": "Center Forward",
    "RCF": "Right Center Forward",
    "LCF": "Left Center Forward",
    "LW": "Left Wing",
    "RW": "Right Wing",
}

ROLE_LONG_TO_SHORT = {
    **{long.lower(): short for short, long in ROLE_SHORT_TO_LONG.items()},
    "g": "GK",
    "goal keeper": "GK",
    "left wing back": "LB",
    "right wing back": "RB",
    "left center back": "CB",
    "right center back": "CB",
    "centre back": "CB",
    "left defensive midfield": "CDM",
    "right defensive midfield": "CDM",
    "defensive midfield": "CDM",
    "left center midfield": "CM",
    "right center midfield": "CM",
    "central midfield": "CM",
    "left attacking midfield": "CAM",
    "right attacking midfield": "CAM",
    "attacking midfield": "CAM",
    "a": "CF",
    "f": "CF",
    "attacker": "CF",
    "forward": "CF",
    "centre forward": "CF",
    "right center forward": "CF",
    "left center forward": "CF",
}

ROLE_SEARCH_SHORT_ALIASES = {
    "LWB": "LB",
    "RWB": "RB",
}

ALLOWED_SELECTION_LEAGUES = [
    "Championship",
    "Eerste Divisie",
    "La Liga",
    "Stars League",
    "Primera Division",
    "Admiral Bundesliga",
    "Bundesliga",
    "2. Bundesliga",
    "Premier League",
    "1. Lig",
    "La Liga 2",
    "Liga Profesional de Fútbol",
    "Serie B",
    "First Division",
    "Major League Soccer",
    "Chance Liga",
    "Veikkausliiga",
    "FNL",
    "Ekstraklasa",
    "Eliteserien",
    "Premiership",
    "First League",
    "Eredivisie",
    "Allsvenskan",
    "Enterprise National League",
    "Liga Portugal",
    "Challenger Pro League",
    "Superliga",
    "Botola Pro",
    "Super League",
    "Liga MX",
    "League One",
    "Ligue 2",
    "League Two",
    "1. HNL",
    "Serie A",
    "Super Lig",
    "Ligue 1",
]

PLAYER_DATA_LEAGUES = {
    '1. HNL',
    '1. Lig',
    '2. Bundesliga',
    'A-League Men',
    'A-League Women',
    'Admiral Bundesliga',
    'Allsvenskan',
    'Botola Pro',
    'Brasileiro Women',
    'Bundesliga',
    'Challenger Pro League',
    'Championship',
    'Chance Liga',
    'Eerste Divisie',
    'Ekstraklasa',
    'Eliteserien',
    'Enterprise National League',
    'Eredivisie',
    'First Division',
    'First League',
    'FNL',
    'Indian Super League',
    'J1 League',
    'K League 1',
    'La Liga',
    'La Liga 2',
    'League One',
    'League Two',
    'Liga MX',
    'Liga Portugal',
    'Liga Profesional de Fútbol',
    "Ligat ha'Al",
    'Ligue 1',
    'Ligue 2',
    'Major League Soccer',
    'Persian Gulf Pro League',
    'Premier League',
    'Premiership',
    'Primera Division',
    'Pro League',
    'Serie A',
    'Serie B',
    'Stars League',
    'Super League',
    'Super Lig',
    'Superliga',
    'UAE Pro League',
    'V-League',
    'Veikkausliiga',
    "Women's Super League",
}

CANONICAL_LEAGUES = set(PLAYER_DATA_LEAGUES)

PLAYER_DATA_TEAMS = {
    '1º Dezembro',
    '2 de Mayo',
    '2 Korriku U19',
    'Aalborg BK',
    'Aalesund',
    'Aarau',
    'Aarhus Fremad',
    'ABC',
    'Aberdeen',
    'Abha',
    'AC Milan',
    'Academia Puerto Cabello',
    'Academico Viseu',
    'Accrington Stanley',
    'AD Marco 09',
    'Adana Demirspor',
    'Adelaide United',
    'Adelaide United W',
    'Admira',
    'ADO Den Haag',
    'AEK Athens',
    'AEK Athens W',
    'AEK Larnaca',
    'AEK Larnaca U19',
    'AF Elbasani',
    'AFC',
    'AFC Bournemouth',
    'AFC Emley',
    'AFC Telford United',
    'AFC Totton',
    'AFC Wimbledon',
    'Afghanistan',
    'AGF',
    'Agram W',
    'Águia de Marabá',
    'Ahal',
    'Ahrobiznes Volochysk',
    'AIK',
    'Ajax',
    'Ajax U19',
    'Ajman',
    'Akhmat Grozny',
    'Akron',
    'Aktobe',
    'Aktobe W',
    'Al Adalah',
    'Al Ahli',
    'Al Ahly',
    'Al Ain',
    'Al Arabi Saudi',
    'Al Bataeh',
    'Al Batin',
    'Al Bukayriyah',
    'Al Dhafra',
    'Al Duhail',
    'Al Ettifaq',
    'Al Faisaly',
    'Al Fateh',
    'Al Gharafa',
    'Al Hazm',
    'Al Hilal',
    'Al Hilal Omdurman',
    'Al Hussein',
    'Al Ittihad',
    'Al Jabalain',
    'Al Jazira',
    'Al Jubail',
    'Al Khaleej',
    'Al Khalidiyah',
    'Al Kholood',
    'Al Masry',
    'Al Najma',
    'Al Nasr',
    'Al Nassr',
    'Al Okhdoud',
    'Al Raed',
    'Al Rayyan',
    'Al Riyadh',
    'Al Sadd',
    'Al Sailiya',
    'Al Seeb',
    'Al Shabab',
    'Al Shahaniya',
    'Al Shamal SC',
    'Al Sharjah',
    'Al Shorta',
    'Al Taawoun',
    'Al Tai',
    'Al Wahda',
    'Al Wakrah',
    'Al Wasl',
    'Al Wihdat',
    "Al Zawra'a",
    'Al Zulfi',
    'Al-Ahli Doha',
    'Al-Arabi SC',
    'Al-Fayha',
    'Al-Orobah FC',
    'Al-Qadsiah',
    'Al-Wehda',
    'Alanyaspor',
    'Alashkert',
    'Albacete',
    'Albania',
    'Albion',
    'Albirex Niigata',
    'Aldershot Town',
    'Aldosivi',
    'Algeria U23',
    'Alianza Atlético',
    'Alianza Lima',
    'Almere City',
    'Almería',
    'Alpendorada',
    'Altglienicke',
    'Altos',
    'Altrincham',
    'Aluminij',
    'Aluminium Arak',
    'Alverca',
    'Always Ready',
    'Amarante',
    'Amazonas',
    'AmaZulu',
    'Amed SK',
    'América',
    'América de Cali',
    'América Mineiro',
    'América Mineiro W',
    'América RN',
    'America SE',
    'Amiens SC',
    'Amkal',
    'Anadia',
    'Anápolis',
    'Anderlecht',
    'Andijan',
    'Andorra',
    'Anenii Noi W',
    'Angers SCO',
    'Annecy',
    'Antalyaspor',
    'Antequera',
    'Antoniano',
    'Antwerp',
    'Anyang',
    'Apollon',
    'Apollon W',
    'Arab Contractors FC',
    'Araguaína',
    'Ararat-Armenia',
    'Araz',
    'Arbroath',
    'Arda',
    'Arenas de Getxo',
    'Argentina',
    'Argentinos Juniors',
    'Argeş',
    'Aris',
    'Aris Limassol',
    'Arka Gdynia',
    'Arkadag',
    'Armenia',
    'Arouca',
    'Arsenal',
    'Arsenal Tula',
    'Arsenal U19',
    'Arsenal W',
    'Aruba',
    'AS Gosier',
    'ASA',
    'ASA Târgu Mureş',
    'Ashdod',
    'Astana',
    'Asteras Tripolis',
    'Aston Villa',
    'Aston Villa U19',
    'Aston Villa W',
    'Astrakhan',
    'Atalanta',
    'Atalanta U19',
    'Atert Bissen',
    'Athletic Club',
    'Athletic Club U19',
    'Athletico PR',
    'Athlone Town WFC W',
    'ATK Mohun Bagan',
    'Atl. Madrid U19',
    'Atlanta United',
    'Atlante',
    'Atlas',
    'Atlas Delmenhorst',
    "Atlètic Club d'Escaldes",
    'Atlètic Lleida',
    'Atlètic Sant Just',
    'Atlético Alagoinhas',
    'Atlético Astorga',
    'Atlético Baleares',
    'Atlético Bucaramanga',
    'Atlético CP',
    'Atlético de Madrid',
    'Atlético GO',
    'Atletico Madrid W',
    'Atlético Mineiro',
    'Atlético Mineiro W',
    'Atlético Nacional',
    'Atlético Progreso',
    'Atlético San Luis',
    'Atlético Tordesillas',
    'Atlético Tucumán',
    'Atromitos',
    'Aucas',
    'Auckland',
    'Auckland City',
    'Audace Cerignola',
    'Audax Italiano',
    'Austin',
    'Australia',
    'Austria Wien',
    'Austria Wien U19',
    'Austria Wien W',
    'Auxerre',
    'Avaí',
    'Avellino',
    'Avispa Fukuoka',
    'Avranches',
    'AVS',
    'Ayr United',
    'AZ',
    'AZ U19',
    'Azerbaijan',
    'Azuaga',
    'Azuriz',
    'B 93',
    'Babelsberg',
    'Bahia',
    'Bahia W',
    'Bahlinger SC',
    'Bahrain',
    'Balingen',
    'Baltika Kaliningrad',
    'Bandırmaspor',
    'Banfield',
    'Banga',
    'Bangladesh',
    'Bani Yas',
    'Baník Ostrava',
    'Banská Bystrica',
    'Barcelona Guayaquil',
    'Barcelona U19',
    'Barcelona W',
    'Baré',
    'Barendrecht',
    'Bari 1908',
    'Barnet',
    'Barnsley',
    'Barra FC',
    'Barracas Central',
    'Barrow',
    'Basel',
    'Basel U19',
    "Bassin d' Arcachon Sud",
    'Bastia',
    'BATE',
    'Bayer 04 Leverkusen',
    'Bayer Leverkusen U19',
    'Bayern München II',
    'Bayern Munich W',
    'Bayern U19',
    'Be1 U19',
    'Becamex Hồ Chí Minh U19',
    'Beijing Guoan',
    'Beitar Jerusalem',
    'Belgrano',
    'Benfica',
    'Benfica U19',
    'Bengaluru',
    'Benin',
    'Bermuda',
    'Beroe',
    'Beşiktaş',
    'Bethune',
    'Betim',
    'BFC Dynamo',
    'BG Pathum United',
    'Biesheim',
    'Birmingham City',
    'Blackburn Rovers',
    'Blackpool',
    'Blau-Weiß Linz',
    'Blois',
    'Blooming',
    'Bnei Sakhnin',
    'Bnei Yehuda',
    'Boavista',
    'Boca Juniors',
    'Bodø / Glimt',
    'Bodø / Glimt U19',
    'Bodrum FK',
    'Bohemians',
    'Bohemians 1905',
    'Bolivia',
    'Bologna',
    'Bolton Wanderers',
    'Boluspor',
    'Borac Banja Luka',
    'Bordeaux',
    'Boreham Wood',
    'Borussia Dortmund',
    'Borussia Dortmund U19',
    'Borussia Mönchengladbach',
    'Boston River',
    'Boston United',
    'Botafogo',
    'Botafogo PB',
    'Botafogo SP',
    'Botafogo W',
    'Botev Plovdiv',
    'Botev Vratsa',
    'Botoşani',
    'Botswana',
    'Boulogne',
    'Bourg-en-Bresse',
    'Brackley Town',
    'Bradford City',
    'Bragantino',
    'Bragantino PA',
    'Braintree Town',
    'Brann',
    'Brann U19',
    'Brann W',
    'Bravo',
    'Bravo U19',
    'Breidablik',
    'Breidablik W',
    'Brentford',
    'Brest',
    'Brighton & Hove Albion',
    'Brighton W',
    'Brisbane Roar',
    'Brisbane Roar W',
    'Bristol City',
    'Bristol Rovers',
    'British Virgin Islands',
    'Broke Boys',
    'Bromley',
    'Brommapojkarna',
    'Brommapojkarna U19',
    'Brøndby IF',
    'Bryne',
    'Bucheon 1995',
    'Budućnost',
    'Budućnost Podgorica w',
    'Budućnost U19',
    'Bukovyna Chernivtsi',
    'Burgos',
    'Buriram United',
    'Burkina Faso',
    'Burnley',
    'Burton Albion',
    'Burundi',
    'Buxton',
    'BW Lohne',
    'Cacereño',
    'Cádiz',
    'Caen',
    'Caernarfon Town',
    'Cagliari',
    'Calcio Padova',
    'Caldas',
    'Cambodia',
    'Cambridge United',
    'Cameroon',
    'Canada',
    'Canberra United W',
    'Canet Roussillon',
    'Cannes',
    'Cape Verde Islands',
    'Capelle',
    'Capital Brasilia',
    'Carabobo',
    'Caracas',
    'Cardiff City',
    'Cardiff City W',
    'Carl Zeiss Jena',
    'Carlisle United',
    'Carrarese',
    'Casa Pia',
    'Casertana',
    'Castanhal',
    'Castellón',
    'Catanzaro',
    'Caudal',
    'Caxias',
    'Cayman Islands',
    'CD Ebro',
    'CE Sant Jordi',
    'Ceará',
    'Ceilândia',
    'Celje',
    'Celoricense',
    'Celta de Vigo',
    'Celtic',
    'Central African Republic',
    'Central Coast Mariners',
    'Central Coast Mariners W',
    'Central Cordoba SdE',
    'Central Español',
    'Ceramica Cleopatra',
    'Cercle Brugge',
    'Cerezo Osaka',
    'Cerro',
    'Cerro Largo',
    'Cerro Porteño',
    'Cesena',
    'Ceuta',
    'CF Montréal',
    'CF Os Belenenses',
    'CFR Cluj',
    'Chad',
    'Chadormalu SC',
    'Changchun Yatai',
    'Chapecoense',
    'Charlotte',
    'Charlton Athletic',
    'Chatham Town',
    'Chauvigny',
    'Chaves',
    'Chayka',
    'Chelmsford City',
    'Chelsea',
    'Chelsea U19',
    'Chelsea W',
    'Cheltenham Town',
    'Chelyabinsk',
    'Chemnitzer FC',
    'Chengdu Rongcheng',
    'Chennaiyin',
    'Cherepovets',
    'Cherno More',
    'Chernomorets',
    'Chester',
    'Chesterfield',
    'Chicago Fire',
    'Chile',
    'China PR',
    'Chinese Taipei',
    'Chippa United',
    'Chongqing Tonglianglong FC',
    'Cianorte',
    'Cienciano',
    'Cieza',
    'Cincinnati',
    'Clermont',
    'Cliftonville W',
    'Club Bolívar',
    'Club Brugge',
    'Club Brugge U19',
    'Club NXT U23',
    'Clyde',
    'Cobresal',
    'CODM Meknès',
    'Colchester United',
    'Colo-Colo',
    'Colorado Rapids',
    'Columbus Crew',
    'Comércio Indústria',
    'Como',
    'Comoros',
    'Concarneau',
    'Confiança',
    'Công an Hà Nội',
    'Công an TP.Hồ Chí Minh',
    'Congo',
    'Congo DR',
    "Connah's Quay",
    'Constància',
    'Coquimbo Unido',
    'Córdoba',
    'Corinthians',
    'Corinthians W',
    'Coritiba',
    'Cork City',
    'Çorum FK',
    'Costa Rica',
    'Coventry City',
    'CR Khemis Zemamra',
    'Cracovia Kraków',
    'Crawley Town',
    'CRB',
    'Cremonese',
    'Crewe Alexandra',
    'Criciúma',
    'Croix Football IC',
    'Cruz Azul',
    'Cruzeiro',
    'Cruzeiro W',
    'Crvena Zvezda',
    'Crvena Zvezda U19',
    'Crystal Palace',
    'CSA',
    'Csikszereda',
    'CSKA 1948 Sofia',
    'CSKA Moskva',
    'CSKA Sofia',
    'Cuiabá',
    'Cultural Leonesa',
    'Cusco FC',
    'Cyprus',
    'Daegu',
    'Daejeon Citizen',
    'Dalian Yingbo',
    'Dallas',
    'Damac FC',
    'Danubio',
    'Darmstadt 98',
    'DC United',
    'De Graafschap',
    'De Treffers',
    'Dečić',
    'Defensa y Justicia',
    'Defensor Sporting',
    'Degerfors',
    'Dender',
    'Deportes Tolima',
    'Deportivo Alavés',
    'Deportivo Cuenca',
    'Deportivo Garcilaso',
    'Deportivo La Coruña',
    'Deportivo La Guaira',
    'Deportivo Maldonado',
    'Deportivo Recoleta',
    'Deportivo Riestra',
    'Deportivo Táchira',
    'Derby County',
    'Derry City',
    'Desportiva ES',
    'Deutschlandsberger SC',
    'Dibba Al Fujairah',
    'Dieppe',
    'Difaâ El Jadida',
    'Differdange 03',
    'Dila',
    'Dinamo Bucureşti',
    'Dinamo City',
    'Dinamo Minsk',
    'Dinamo Minsk U19',
    'Dinamo Moskva',
    'Dinamo Tbilisi',
    'Dinamo Tbilisi U19',
    'Dinamo Zagreb',
    'Dinamo-BGU W',
    'Djibouti',
    'Djurgården',
    'Dobrudzha 1919',
    'Dominican Republic',
    'Doncaster Rovers',
    'Đông Á Thanh Hoá',
    'DOVO',
    'Drita',
    'DSC Arminia Bielefeld',
    'Dukla Praha',
    'Dumbarton',
    'Dunav 2010',
    'Dundee',
    'Dundee United',
    'Dunfermline Athletic',
    'Dungannon Swifts',
    'Dunkerque',
    'Durban City',
    'Dynamo Dresden',
    'Dynamo Kyiv',
    'Dynamo Kyiv U19',
    'Dynamo Makhachkala',
    'East Bengal',
    'Eastern',
    'Eastleigh',
    'Ebbsfleet United',
    'Eemdijk',
    'Egnatia Rrogozhinë',
    'Eintracht Braunschweig',
    'Eintracht Frankfurt',
    'Eintracht Frankfurt U19',
    'Eintracht Frankfurt W',
    'Eintracht Norderstedt',
    'El Geish',
    'El Gounah',
    'El Salvador',
    'Elche',
    'Eldense',
    'Elfsborg',
    'Elgin City',
    'Elversberg',
    'Empoli',
    'Energie Cottbus',
    'ENPPI',
    'Epitsentr Dunayivtsi',
    'Equatorial Guinea',
    'Erzurumspor FK',
    'ES Tunis',
    'Esbjerg',
    'Esenler Erokspor',
    'Espanyol',
    'Esteghlal',
    'Esteghlal Khuzestan',
    'Estonia',
    'Estoril',
    'Estrela Amadora',
    'Estudiantes',
    'Estudiantes de Río Cuarto',
    'Eswatini',
    'Ethiopia',
    'Europa',
    'Europa FC',
    'Everton',
    'Everton W',
    'Excelsior',
    'Excelsior Maassluis',
    'Exeter City',
    'Extremadura 1924',
    'Eyüpspor',
    'Fafe',
    'Fagiano Okayama',
    'Fajr Sepasi',
    'Fakel',
    'Falkirk',
    'Famalicão',
    'FAR Rabat',
    'Farense',
    'Farul Constanța',
    'Farul Constanţa W',
    'Farum BK W',
    'Fatih Karagümrük',
    'FC Andorra',
    'FC Augsburg',
    'FC Barcelona',
    'FC Bayern München',
    'FC Cartagena',
    'FC Den Bosch',
    'FC Dordrecht',
    'FC Eindhoven',
    'FC Emmen',
    'FC Gießen',
    'FC Groningen',
    'FC Gütersloh',
    'FC Iberia 1999',
    'FC København',
    'FC Köln',
    'FC Metalist Kharkiv',
    'FC Midtjylland',
    'FC Santa Coloma',
    'FC Tokyo',
    'FC Twente',
    'FC Twente W',
    'FC Union Berlin',
    'FC Utrecht',
    'FC Volendam',
    'FCSB',
    'FCSB U19',
    'Feignies-Aulnoye',
    'Felgueiras 1932',
    'Fenerbahçe',
    'Ferencvárosi',
    'Ferencvárosi W',
    'Ferroviária',
    'Ferroviária W',
    'Feyenoord',
    'Figueirense',
    'Fiji',
    'Fiorentina',
    'Fiorentina U20',
    'FK Košice',
    'FK Nizjni Novgorod',
    'Flamengo',
    'Flamengo W',
    'Fleetwood Town',
    'Fleury 91',
    'Flora',
    'Flora W',
    'Floriana',
    'Fluminense',
    'Fluminense PI',
    'Fluminense W',
    'Fomget Gençlik W',
    'Fontenay Vendée Foot',
    'Foolad',
    'Forest Green Rovers',
    'Fortaleza',
    'Fortuna Düsseldorf',
    'Fortuna Hjorring W',
    'Fortuna Sittard',
    'Fredericia',
    'Fredrikstad',
    'Freyming',
    'Frosinone',
    'FS Jelgava U19',
    'FSV Mainz 05',
    'Fulham',
    'FUS Rabat',
    'FV Engers 07',
    'Gabon',
    'Gainsborough Trinity',
    'GAIS',
    'Galatasaray',
    'Galatasaray U19',
    'Galvez',
    'Gama',
    'Gamba Osaka',
    'Gambia',
    'Gangwon',
    'GAS',
    'Gateshead',
    'Gaziantep F.K.',
    'Gemert',
    'Gençlerbirliği',
    'Genemuiden',
    'Genk',
    'Genk U19',
    'Genoa',
    'Gent',
    'Getafe',
    'Getxo',
    'Ghana',
    'Ghazl El Mehalla',
    'Gibraltar',
    'Gil Vicente',
    'Gillingham',
    'Gimcheon Sangmu',
    'Gimnasia La Plata',
    'Gimnasia y Esgrima Mendoza',
    'Gimnàstic Tarragona',
    'Gintra W',
    'Girona',
    'GKS Katowice W',
    'Glasgow City W',
    'Glentoran',
    'Gnistan',
    'Go Ahead Eagles',
    'Goa',
    'Godoy Cruz',
    'Goiás',
    'Gol Gohar',
    'Golden Arrows',
    'Gorica',
    'Górnik Zabrze',
    'Gotham FC W',
    'Göztepe',
    'Granada',
    'Grasshopper',
    'Grazer AK',
    'Greece',
    'Grêmio',
    'Grêmio W',
    'Grenada',
    'Grenoble Foot 38',
    'Grimsby Town',
    'Guabirá',
    'Guadalajara',
    'Guaporé',
    'Guarani',
    'Guaraní',
    'Guarany de Bagé',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guingamp',
    'GVVV',
    'Gwangju',
    'Győri ETO',
    'Hà Nội',
    'Häcken',
    'Häcken W',
    'Hải Phòng',
    'Haiti',
    'Hajduk Split',
    'Haka',
    'Halifax Town',
    'Hallescher FC',
    'Halmstad',
    'Halsteren',
    'Hamburger SV',
    'HamKam',
    'Hammarby',
    'Hammarby W',
    'Hamrun Spartans',
    'Hanácká',
    'Hannover 96',
    'Hansa Rostock',
    "Hapoel Be'er Sheva",
    'Hapoel Haifa',
    'Hapoel Jerusalem',
    'Hapoel Petah Tikva',
    'Hapoel Tel Aviv',
    'Haras El Hodood',
    'Harrogate Town',
    'Hartberg',
    'Hartlepool United',
    'Hassania Agadir',
    'Hatayspor',
    'Haugesund',
    'Hauts Lyonnais',
    'Havant & Waterlooville',
    'Haverfordwest U19',
    'HB',
    'HB Køge',
    'Hearts',
    'Hegelmann Litauen',
    'Heidenheim',
    'Hellas Verona',
    'Helmond Sport',
    'Hemel Hempstead Town',
    'Hemelingen',
    'Henan Songshan Longmen',
    'Heracles Almelo',
    'Hermannstadt',
    'Hertha BSC',
    'HHC',
    'Hibernian',
    'Hibernian U19',
    'Hibernian W',
    'Hibernians',
    'Hillerød',
    'HJK',
    'HJK U19',
    'HJK W',
    'Hoàng Anh Gia Lai',
    'Hobro',
    'Holstein Kiel',
    'Homburg',
    'Honduras',
    'Hong Kong',
    'Hồng Lĩnh Hà Tĩnh',
    'Hoogeveen',
    'Horsens',
    'Houston Dynamo',
    'Hradec Králové',
    "HSC '21",
    'HSV Hoek',
    'Huachipato',
    'Huddersfield Town',
    'Huesca',
    'Hull City',
    'Huracán',
    'Hvidovre',
    'Iape',
    'IFK Göteborg',
    'Iğdır FK',
    'Illertissen',
    'Ilves',
    'Imperatriz',
    'Incheon United',
    'Independencia',
    'Independente AP',
    'Independiente',
    'Independiente del Valle',
    'Independiente Medellín',
    'Independiente Petrolero',
    'Independiente Rivadavia',
    'Indonesia',
    'Instituto',
    'Inter',
    'Inter Bratislava',
    "Inter Club d'Escaldes",
    'Inter de Valdemoro',
    'Inter Kashi',
    'Inter Miami',
    'Inter Milano W',
    'Inter Turku',
    'Inter U19',
    'Internacional',
    'Internacional RS W',
    'Ipswich Town',
    'Iraq',
    'Irkutsk',
    'Ironi Kiryat Shmona',
    'Ironi Tiberias',
    'Ismaily',
    'İstanbul Başakşehir',
    'İstanbulspor',
    'Istiqlol Dushanbe',
    'Istra 1961',
    'Istres',
    'Itabaiana',
    'Italy',
    'Ittihad Tanger',
    'Ivinhema',
    'Jablonec',
    'Jacuipense',
    'Jagiellonia Białystok',
    'Jahn Regensburg',
    'Jamshedpur',
    'Jaro',
    'Jeddah',
    'Jeju United',
    'Jeonbuk Motors',
    'Ji-Paraná',
    "Johor Darul Ta'zim",
    'Joinville',
    'Jong Ajax',
    'Jong AZ',
    'Jong FC Utrecht',
    'Jong Gent',
    'Jong KRC Genk U23',
    'Jong PSV',
    'Jordan',
    'JS Kabylie',
    'Juárez',
    'Juazeirense',
    'Junior FC',
    'Juve Stabia',
    'Juventud',
    'Juventud Torremolinos',
    'Juventude',
    'Juventude W',
    'Juventus',
    'Juventus U19',
    'Juventus W',
    'K. Beerschot V.A.',
    'KA Akureyri',
    'KA U19',
    'Kahraba Ismailia',
    'Kairat',
    'Kairat U19',
    'Kaiserslautern',
    'Kaizer Chiefs',
    'Kalba',
    'Kalmar',
    'KAMAZ',
    'Kansas City Current W',
    'Karlsruher SC',
    'Karpaty',
    'Karviná',
    'KAS Eupen',
    'Kashima Antlers',
    'Kashiwa Reysol',
    'Kasımpaşa',
    'Katowice',
    'Katwijk',
    'Kauno Žalgiris',
    'Kawasaki Frontale',
    'Kawkab Marrakech',
    'Kaya',
    'Kayserispor',
    'Kazakhstan',
    'Keçiörengücü',
    'Kelty Hearts',
    'Kenya',
    'Kerala Blasters',
    'KF Ballkani',
    'KFUM',
    'Kheybar Khorramabad',
    'Khorfakkan Club',
    'KÍ',
    'Kickers Emden',
    'Kifisia',
    'Kilmarnock',
    "King's Lynn Town",
    'Kiryat Gat W',
    'København U19',
    'Kocaelispor',
    'Kolding IF',
    'Koln U19',
    'Kolos Kovalivka',
    'Komárno',
    'Koninklijke HFC',
    'Koninklijke Lierse Sportkring',
    'Konyaspor',
    'Koper',
    'Korea Republic',
    'Korona Kielce',
    'Kosovo',
    'Krasnodar',
    'Kristiansund',
    'Krylya Sovetov',
    'Kryvbas Kryvyi Rih',
    'KSC Lokeren',
    'KTP',
    'Kuban Kholding',
    'Kudrivka',
    'KuPS',
    'Kuwait',
    'KV Kortrijk',
    'Kyoto Sanga',
    'Kyrgyz Republic',
    'La Fiorita',
    'LA Galaxy',
    'La Louvière',
    'La Union Atletico',
    'Lagarto',
    'Laguna',
    'Lahti',
    'Lanchkhuti',
    'Langreo',
    'Lanús',
    'Larissa',
    'Larne',
    'Larne U19',
    'Las Palmas',
    'LASK Crvena Zvezda W',
    'LASK Linz',
    'Lausanne Sport',
    'Laval',
    'Lazio',
    'LDU Quito',
    'Le Havre',
    'Le Mans',
    'Le Puy-en-Velay',
    'Lebanon',
    'Lebring',
    'Lecce',
    'Lech Poznań',
    'Lechia Gdańsk',
    'Leeds United',
    'Leganés',
    'Legia Warszawa',
    'Legia Warszawa U19',
    'Leicester City',
    'Leicester W',
    'Leixões',
    'Leningradets',
    'Lens',
    'León',
    'Les Herbiers',
    'Les Sables',
    'Lesotho',
    'Levadia',
    'Levadiakos',
    'Levante',
    'Levski Sofia',
    'Leyton Orient',
    'Liaoning Tieren FC',
    'Liberia',
    'Libertad',
    'Libya',
    'Liechtenstein',
    'Liepāja',
    'Lillestrøm',
    'Lincoln City',
    'Lincoln Red Imps',
    'Lincoln Red Imps U19',
    'Linfield',
    'Lion City Sailors FC',
    'Lisse',
    'Liverpool',
    'Liverpool U19',
    'Liverpool W',
    'Livingston',
    'Livyi Bereh',
    'Ljuboten W',
    'LNZ Cherkasy',
    'Lokomotiv Moskva',
    'Lokomotiv Plovdiv',
    'Lokomotiv Sofia 1929',
    'Lokomotiva Zagreb',
    'Lokomotiva Zagreb U19',
    'Lokomotive Leipzig',
    'Lommel SK',
    'London City Lionesses W',
    'Londrina',
    'Lorca Deportiva',
    'Lorient',
    'Los Angeles FC',
    'Los Garres',
    'LOSC Lille',
    'Louisville City',
    'Louletano',
    'Lucena',
    'Ludogorets',
    'Ludogorets U19',
    'Lugano',
    'Lusitania FC Lourosa',
    'Lusitano Évora 1911',
    'Luton Town',
    'Luxembourg',
    'Luzern',
    'Lyngby Boldklub',
    'Lyon Duchère',
    'Macao',
    'Macará',
    'Macarthur',
    'Maccabi Bnei Raina',
    'Maccabi Haifa',
    'Maccabi Haifa U19',
    'Maccabi Netanya',
    'Maccabi Tel Aviv',
    'Macclesfield',
    'Machida Zelvia',
    'Madagascar',
    'Madureira',
    'Magdeburg',
    'Magesi',
    'Maghreb Fès',
    'Maguary PE',
    'Málaga',
    'Malavan',
    'Malawi',
    'Malaysia',
    'Maldon & Tiptree',
    'Malisheva',
    'Mallorca',
    'Malmö FF',
    'Malta',
    'Mamelodi Sundowns',
    'Manauara',
    'Manaus',
    'Manchester City',
    'Manchester City U19',
    'Manchester City W',
    'Manchester United',
    'Manchester United W',
    'Manila Digger',
    'Manisa FK',
    'Mansfield Town',
    'Mantova',
    'Maracanã',
    'Maracena',
    'Maranhão',
    'Maribor',
    'Mariehamn',
    'Maringá',
    'Marinhense',
    'Marsaxlokk',
    'Marumo Gallants FC',
    'Mauritania',
    'Mauritius',
    'Mazatlán',
    'MC Alger',
    'Mechelen',
    'Meizhou Hakka',
    'Melbourne City',
    'Melbourne City W',
    'Melbourne Victory',
    'Melbourne Victory W',
    'Melgar',
    'Merida',
    'Mes Rafsanjan',
    'Metalist 1925 Kharkiv',
    'Metalist 1925 Kharkiv W',
    'Metaloglobus',
    'Metropolitanos',
    'Metz',
    'Middelfart',
    'Middlesbrough',
    'Midtjylland U19',
    'Miedź Legnica',
    'Millonarios',
    'Millwall',
    'Milsami',
    'Milton Keynes Dons',
    'Minerva Punjab',
    'Minnesota United',
    'Minsk FK W',
    'Miramar Misiones',
    'Mirandés',
    'Mirassol',
    'Mitrovica W',
    'Mixto',
    'Mixto W',
    'Mjällby',
    'ML Vitebsk',
    'Mladá Boleslav',
    'Modena',
    'Modern Sport FC',
    'Mohammedan',
    'Molde',
    'Moldova',
    'Monaco',
    'Monaco U19',
    'Monagas',
    'Mondorf-les-Bains',
    'Montana',
    'Monte Roraima',
    'Monterrey',
    'Montevideo City Torque',
    'Montpellier',
    'Montreuil FC',
    'Monza',
    'Morecambe',
    'Moreirense',
    'Mornar',
    'Mortágua',
    'Motherwell',
    'Motor Lublin',
    'MSV Duisburg',
    'MTE 1904',
    'Muharraq',
    'Mumbai City',
    'Mushuc Runa',
    'Mutilvera',
    'MVV Maastricht',
    'NAC Breda',
    'Nacional',
    'Nacional AM',
    'Nacional Asunción',
    'Nacional Potosí',
    'Nafta',
    'Nagoya Grampus',
    'Nairn County',
    'Namibia',
    'Nancy',
    'Nantes',
    'Nantes U19',
    'Napoli',
    'Napoli U19',
    'Nasaf',
    'Nashville SC',
    'National Bank of Egypt',
    'Náutico',
    'Navalcarnero',
    'Naxara CD',
    'Naxxar Lions FC U19',
    'NEC Nijmegen',
    'Necaxa',
    'Neftchi',
    'Neftçi',
    'Neftçi Bakı W',
    'Neftekhimik',
    'Negreira',
    'Neman Grodno',
    'NEOM SC',
    'Nepal',
    'New Caledonia',
    'New England',
    'New York City',
    'New York RB',
    'Newcastle Jets',
    'Newcastle Jets W',
    'Newcastle United',
    'Newcastle United U19',
    "Newell's Old Boys",
    'Newport County',
    'Nicaragua',
    'Nice',
    'Nieciecza',
    'Niger',
    'Nigeria',
    'Ninh Bình',
    'Noah',
    'Nõmme Kalju',
    'Nordsjælland',
    'Norrköping',
    'North Macedonia',
    'Northampton Town',
    'NorthEast United',
    'Northern Ireland',
    'Norwich City',
    'Nottingham Forest',
    'Notts County',
    'Nova Iguaçu',
    'Novi Pazar',
    'Novorizontino',
    'NSA Sofia W',
    'NSÍ',
    'NSÍ W',
    'Numancia',
    'Nürnberg',
    "O'Higgins",
    "Obolon'-Brovar",
    'OC Charleroi',
    'Odense BK',
    'Odisha FC',
    'Odra Opole',
    'OFI',
    'OH Leuven',
    'OH Leuven W',
    'OL Lyonnes W',
    'Oldham Athletic',
    'Oleksandria',
    'Olimpia',
    'Olimpija',
    'Olot',
    'Olympiacos F.C.',
    'Olympiacos F.C. U19',
    'Olympic Safi',
    'Olympique Dcheïra',
    'Olympique Lyonnais',
    'Olympique Marseille',
    'Olympique Marseille U19',
    'Oman',
    'Omonia Nicosia',
    'Once Caldas',
    'Operário Ltda',
    'Operário MS',
    'Operário PR',
    'Oratório',
    'Orbit College',
    'Orenburg',
    'Orense',
    'Örgryte',
    'Orihuela',
    'Orlando City',
    'Orlando Pirates',
    'Orléans',
    'Osasuna',
    'Osijek',
    'Osnabrück',
    'Öster',
    'Ostrava U19',
    'Otelul',
    'Oulu',
    'Ourense CF',
    'Oxford United',
    'Pachuca',
    'Paços de Ferreira',
    'Paderborn',
    'Pafos FC',
    'Pafos U19',
    'Paide',
    'Pakistan',
    'Paksi SE',
    'Palermo',
    'Palestine',
    'Palestino',
    'Palma del Río',
    'Palmeiras',
    'Palmeiras W',
    'Panaitolikos',
    'Panama',
    'Panathinaikos',
    'Panserraikos',
    'PAOK',
    'PAOK U19',
    'Paraguay',
    'Pardubice',
    'Paris',
    'Paris Saint Germain',
    'Paris SG U19',
    'Paris SG W',
    'Paris W',
    'Parma',
    'Partick Thistle',
    'Partizan',
    'Patro Eisden Maasmechelen',
    'Pau',
    'Paykan',
    'Paysandu',
    'PEC Zwolle',
    'Peñarol',
    'Pendikspor',
    'Penedense',
    'Penybont',
    'Persepolis',
    'Persib',
    'Perth Glory',
    'Perth Glory W',
    'Peru',
    'Pescara',
    'Peterborough United',
    'Petro de Luanda',
    'Petrocub',
    'Petrojet',
    'Petrolul 52',
    'Petrovac',
    'Pharco',
    'Philadelphia Union',
    'Piast Gliwice',
    'Piauí',
    'Pirmasens',
    'Pisa',
    'Platense',
    'Plaza Colonia',
    'Plymouth Argyle',
    'Poblense',
    'Pogon Grodzisk Mazowiecki',
    'Pogoń Siedlce',
    'Pogoń Szczecin',
    'Pohang Steelers',
    'Pohronie',
    'Polissya Zhytomyr',
    'Polokwane City',
    'Polonia Warszawa',
    'Ponferradina',
    'Ponte Preta',
    'Pontevedra',
    'Pontivy GSI',
    'Port Vale',
    'Portimonense SAD',
    'Portimonense SC',
    'Portland Timbers',
    'Porto',
    'Porto BA',
    'Porto U19',
    'Porto Velho',
    'Porto Vitória',
    'Portsmouth',
    'Portugalete',
    'Portuguesa',
    'Portuguesa MS',
    'Portuguesa RJ',
    'Power Dynamos',
    'Preston North End',
    'Preußen Münster',
    'Primavera Atlético Clube',
    'Primavera SP',
    'Prishtina',
    'PSV',
    'PSV U19',
    'PSV W',
    'Puebla',
    'Puente Genil',
    'Puerto de Vega',
    'Puerto Rico',
    'Pumas UNAM',
    'Puskás',
    'Puskás Akadémia U19',
    'PVF-CAND',
    'Pyramids FC',
    'Pyunik',
    'Pyunik W',
    'Qarabağ',
    'Qarabag U19',
    'Qatar',
    'Qatar SC',
    'Qingdao Hainiu',
    'Qingdao West Coast',
    'Queens Park Rangers',
    'Querétaro',
    'Quick Boys',
    'Quintanar del Rey',
    'R. Union SG U19',
    'Rabotnički U19',
    'Racing',
    'Racing Club',
    'Racing Ferrol',
    'Racing Santander',
    'Racing Union U19',
    'Racing W',
    'Radnički Kragujevac',
    'Radnik Surdulica',
    'Radomiak Radom',
    'Radomlje',
    'Raja Casablanca',
    'Raków Częstochowa',
    'Randers FC',
    'Rangers',
    "Raon l'Etape",
    'Rapid Bucuresti',
    'Rapperswil-Jona',
    'Ratchaburi Mitrphol FC',
    'Rayo Majadahonda',
    'Rayo Vallecano',
    'RB Bragantino W',
    'RB Leipzig',
    'Reading',
    'Real Ávila',
    'Real Avilés',
    'Real Betis',
    'Real Betis U19',
    'Real Jaén',
    'Real Madrid',
    'Real Madrid U19',
    'Real Madrid W',
    'Real Murcia',
    'Real Oviedo',
    'Real Salt Lake',
    'Real Sociedad',
    'Real Sociedad II',
    'Real Valladolid',
    'Real Zaragoza',
    'Red Star',
    'Reddis',
    'Regar-TadAZ',
    'Reggiana',
    'Reims',
    'Remo',
    'Rennes',
    'Republic of Ireland',
    'Retrô',
    'RFC Liège',
    'RFC Seraing',
    'Rheindorf Altach',
    'Richards Bay',
    'Ried',
    'Riga',
    'Riga W',
    'Rīgas FS',
    'Rijeka',
    'Rijnsburgse Boys',
    'Rimini',
    'Rio Ave',
    'Rio Branco ES',
    'River Plate',
    'Rivers United',
    'Rizespor',
    'RKAV Volendam',
    'RKC Waalwijk',
    'Rochdale',
    'Roda',
    'Roda JC Kerkrade',
    'Rodez',
    'Rodina Moskva',
    'ROHDA Raalte',
    'Roma',
    'Roma W',
    'Rosario Central',
    'Rosenborg',
    'Rosengard W',
    'Rostov',
    'Rot-Weiss Essen',
    'Rot-Weiß Oberhausen',
    'Rotherham United',
    'Rotor Volgograd',
    'Royal Francs Borains',
    'RSB Berkane',
    'RSCA Futures U23',
    'RSD Alcalá',
    'RSV Eintracht',
    'Rubin Kazan',
    'Rukh Vynnyky',
    'Russia',
    'Ružomberok',
    'Rwanda',
    'RWDM Brussels',
    'SA Merignac',
    'Saarbrücken',
    'Sabadell',
    'Sabah',
    'Sabah U19',
    'Saint Eloi Lupopo',
    'Saint-Cyr Collonges',
    'Saint-Étienne',
    'Saint-Priest',
    'Sakaryaspor',
    'Salford City',
    'Salzburg',
    'Samano',
    'Sampaio Corrêa RJ',
    'Sampdoria',
    'Samsunspor',
    'San Antonio Bulo Bulo',
    'San Diego',
    'San Lorenzo',
    'San Marino',
    'San Martín San Juan',
    'Sandefjord',
    'Sandhausen',
    'Sanfrecce Hiroshima',
    'Sant Andreu',
    'Santa Catarina',
    'Santa Clara',
    'Santa Cruz',
    'Santa Fe',
    'Santos',
    'Santos Laguna',
    'Santos W',
    'São Bernardo',
    'Sao Joao Ver',
    'São Luiz',
    'São Paulo',
    'São Paulo W',
    'São Tomé and Príncipe',
    'Sarajevo',
    'Sarıyer SK',
    'Sarmiento',
    'Sarpsborg 08',
    'Sassuolo',
    'SC Cambuur',
    'SC Freiburg',
    'SC Heerenveen',
    'Schalke 04',
    'Schalke 04 II',
    'Schöningen',
    'Schweinfurt',
    'Scunthorpe United',
    'SD Eibar',
    'SD Logroñés',
    'Seattle Sounders',
    'Seekirchen',
    'Sekhukhune United',
    'Selangor',
    'Senegal',
    'Seoul',
    'Sepahan',
    'Septemvri Sofia',
    'Serbia',
    'Serik Belediyespor',
    'Serra Branca',
    'Servette',
    'Sevilla',
    'Seychelles',
    'SF Baumberg',
    'SFK 2000 W',
    'Shabab Al Ahli Dubai',
    'Shakhtar Donetsk',
    'Shamrock Rovers',
    'Shams Azar Qazvin',
    'Shandong Taishan',
    'Shanghai Port',
    'Shanghai Shenhua',
    'SHB Đà Nẵng',
    'Sheffield United',
    'Sheffield Wednesday',
    'Shelbourne',
    'Shelbourne U19',
    'Shenzhen Peng City',
    'Sheriff',
    'Shimizu S-Pulse',
    'Shinnik',
    'Shonan Bellmare',
    'Shrewsbury Town',
    'Sierra Leone',
    'Sigma Olomouc',
    'Sileks',
    'Silkeborg IF',
    'Silves FC',
    'Simba',
    'Singapore',
    'Sint-Truiden',
    'Sintrense',
    'Sion',
    'Sirius',
    'Sivasspor',
    'Siwelele',
    'SJ Earthquakes',
    'SJK',
    'SK Artis Brno',
    'SK Beveren',
    'SK Poltava',
    'SK Rapid',
    'SKA Khabarovsk',
    'Skalica',
    'Skënderbeu U19',
    'Skendija 79',
    'SL Benfica W',
    'Śląsk Wrocław',
    'Slaven Koprivnica',
    'Slavia Prague U19',
    'Slavia Praha',
    'Slavia Praha W',
    'Slavia Sofia',
    'Slough Town',
    'Slovácko',
    'Slovan Bratislava',
    'Slovan Liberec',
    'Smouha',
    'Sochaux',
    'Sochi',
    'Sokol Saratov',
    'Solihull Moors',
    'Solomon Islands',
    'Somalia',
    'Sønderjyske Fodbold',
    'Sông Lam Nghệ An',
    'Sonnenhof Großaspach',
    'Sousa',
    'South Shields',
    'South Sudan',
    'Southampton',
    'Southend United',
    'Spaeri',
    'Spakenburg',
    'Sparta Nijkerk',
    'Sparta Praha',
    'Sparta Praha B',
    'Sparta Praha W',
    'Sparta Rotterdam',
    'Spartak Kostroma',
    'Spartak Moskva',
    'Spartak Myjava W',
    'Spartak Trnava',
    'Spartak Varna',
    'Spennymoor Town',
    'Spezia',
    'Sport Recife',
    'Sportfreunde Lotte',
    'Sportfreunde Siegen',
    'Sporting Braga',
    'Sporting Braga W',
    'Sporting Charleroi',
    'Sporting Covilhã',
    'Sporting CP',
    'Sporting CP U19',
    'Sporting Cristal',
    'Sporting Delhi',
    'Sporting Gijón',
    'Sporting KC',
    'Sporting W',
    'Sportivo Trinidense',
    "Sportlust '46",
    'SpVgg Greuther Fürth',
    'Sri Lanka',
    'St Albans City',
    'St Josephs FC',
    'St Maur Lusitanos',
    "St Patrick's",
    'St. Gallen',
    'St. Kitts and Nevis',
    'St. Louis City',
    'St. Lucia',
    'St. Mirren',
    'St. Pauli',
    'St. Polten W',
    'St. Vincent and the Grenadines',
    'Stade Malien Bamako',
    'Standard Liège',
    'Start',
    'Stellenbosch',
    'Stevenage',
    'Stjarnan',
    'Stockport County',
    'Stoke City',
    'Strasbourg',
    'Strømsgodset',
    'Sturm Graz',
    'Sudan',
    'Südtirol',
    'Sunderland',
    'Suriname',
    'Sutjeska',
    'Sutton United',
    'Suwon',
    'Swansea City',
    'Swieqi United W',
    'Swindon Town',
    'Sydney',
    'Sydney FC W',
    'Syria',
    'Táborsko',
    'Tajikistan',
    'Talavera CF',
    'Talleres Córdoba',
    'Tampines Rovers',
    'Tamworth',
    'Tanzania',
    'Tarazona',
    'Tatran Prešov',
    'Tekstilshchik',
    'Telstar',
    'Tenerife',
    'Teplice',
    'Ternana',
    'Teruel',
    'Thailand',
    'Thể Công-Viettel',
    'The New Saints',
    'The Strongest',
    'Thép Xanh Nam Định',
    'Thun',
    'Tianjin Jinmen Tiger',
    'Tigre',
    'Tigres UANL',
    'Tijuana',
    'Tirol',
    'Tocantinópolis',
    'Togo',
    'Tokyo Verdy',
    'Toledo',
    'Toluca',
    'Tombense',
    'Tondela',
    'TOP Oss',
    'Torino',
    'Toronto',
    'Torpedo BelAZ',
    'Torpedo Kutaisi',
    'Torpedo Moskva',
    'Torreense',
    'Torrent',
    'Tottenham Hotspur',
    'Tottenham Hotspur U19',
    'Tottenham W',
    'Toulouse',
    'TPS',
    'Trabzonspor',
    'Trabzonspor U19',
    'Tractor Sazi',
    'Tranmere Rovers',
    'Tre Fiori',
    'Trem',
    'Trenčín',
    'Trinidad and Tobago',
    'Tromsø',
    'Tropezón',
    'Troyes',
    'True Bangkok United',
    'Truro City',
    'TS Galaxy',
    'TSG Hoffenheim',
    'TSV Steinbach',
    'Tuna Luso',
    'Tunisia',
    'Uberlândia',
    'UCAM Murcia',
    'UCV',
    'UD Ibiza',
    'UD Logroñés',
    'UD Oliveirense',
    'UD Ourense',
    'UD San Fernando',
    'Udinese',
    'Ufa',
    'Uganda',
    'Újpest',
    'Ulm',
    'Ulsan HD',
    'Umm-Salal SC',
    'Ümraniyespor',
    'UNA Strassen',
    'União de Leiria',
    'Union Estepona',
    'Union Saint-Gilloise',
    'Unión Santa Fe',
    'Unirea Slobozia',
    'Universidad Católica',
    'Universidad Chile',
    'Universitario',
    'Universitatea Cluj',
    'Universitatea Craiova',
    'Ural',
    'Urawa Reds',
    'US Chantilly',
    'Ústí nad Labem',
    'USV St. Anna',
    'UTA Arad',
    'Utebo FC',
    'UTS Rabat',
    'Vaduz',
    'Valencia',
    'Vålerenga',
    'Vålerenga W',
    'Valle Egüés',
    'Valur',
    'Valur W',
    'Vancouver Whitecaps',
    'Vanspor FK',
    'Vaprus',
    'Varaždin',
    'Vardar',
    'Värnamo',
    'Vasco da Gama',
    'Vasco da Gama AC',
    'Västerås SK',
    'Vejle Boldklub',
    'Veles',
    'Velez',
    'Vélez Sarsfield',
    'Velo Clube',
    'Venezia',
    'Venezuela',
    'Verden 04',
    'Veres',
    'Verl',
    'Vestri',
    'VfB Lübeck',
    'VfB Stuttgart',
    'VfL Bochum 1848',
    'VfL Wolfsburg',
    'Vianense',
    'Viborg FF',
    'Vicenza',
    'Vietnam',
    'Viking',
    'Víkingur',
    'Vikingur Gota U19',
    'Víkingur Reykjavík',
    'Viktoria Köln',
    'Viktoria Plzeň',
    'Vila Mea',
    'Vila Nova',
    'Villarreal',
    'Villarreal U19',
    'Virtus',
    'Virtus Entella',
    'Vissel Kobe',
    'Vitesse',
    'Vitória',
    'Vitória BA W',
    'Vitória Guimarães',
    'Vllaznia Shkodër',
    'Vllaznia W',
    'Vojvodina',
    'Volga Ulyanovsk',
    'Volgar Astrakhan',
    'Volna Kovernino',
    'Volos NFC',
    'Volta Redonda',
    'Voluntari',
    'Vorskla Poltava W',
    'VPS',
    'Vukovar',
    'VVV-Venlo',
    'Vysočina Jihlava',
    'Wadi Degla',
    'Wales',
    'Walsall',
    'Wanderers',
    'Warta Poznań',
    'Watford',
    'Wealdstone',
    'Wehen Wiesbaden',
    'Wellington Phoenix',
    'Wellington Phoenix W',
    'Werder Bremen',
    'West Bromwich Albion',
    'West Ham United',
    'West Ham W',
    'Westerlo',
    'Western Sydney Wanderers',
    'Western Sydney Wanderers W',
    'Weston-super-Mare',
    'Widzew Lodz',
    'Wigan Athletic',
    'Willem II',
    'Winterthur',
    'Wisła Kraków',
    'Wisła Płock',
    'Wofoo Tai Po',
    'Woking',
    'Wolfsberger AC',
    'Wolfsburg W',
    'Wolverhampton Wanderers',
    'Wrexham',
    'WSG Tirol',
    'WSPG Wels',
    'Wuhan Three Towns',
    'Wuppertaler SV',
    'Wycombe Wanderers',
    'Wydad Casablanca',
    'Yacoub El Mansour',
    'Yantra 1919',
    'Yelimay Semey',
    'Yenisey',
    'Yeovil Town',
    'Yokohama',
    'Yokohama F. Marinos',
    'York City',
    'Young Africans',
    'Young Boys',
    'Young Boys W',
    'Ypiranga Erechim',
    'Yuncos',
    'Yunnan Yukun',
    'Yverdon Sport',
    'Zagłębie Lubin',
    'Žalgiris',
    'Zamalek',
    'Zambia',
    'ZED FC',
    'Železničar Pančevo',
    'Zeljeznicar',
    'Zemplín Michalovce',
    'Zenit',
    'ZFC Meuselwitz',
    'Zhejiang',
    'Žilina',
    'Žilina U19',
    'Zimbabwe',
    'Zimbru',
    'Zira',
    'Zlín',
    'Znamya Truda',
    'ŽNK Mura W',
    'Zob Ahan',
    'Zorya Luhansk',
    'Zrinjski',
    'Zrinjski U19',
    'Zulte-Waregem',
    'Zürich',
}

MANUAL_SOURCE_TEAM_ALIASES = {
    'fenerbahce': 'Fenerbahçe',
    'fenerbahçe': 'Fenerbahçe',
    'galatasaray': 'Galatasaray',
    'besiktas': 'Beşiktaş',
    'beşiktaş': 'Beşiktaş',
    'trabzonspor': 'Trabzonspor',
    'manchester city': 'Manchester City',
    'man city': 'Manchester City',
    'bayern': 'FC Bayern München',
    'bayern munich': 'FC Bayern München',
    'real madrid': 'Real Madrid',
    'barcelona': 'FC Barcelona',
    'psg': 'Paris Saint Germain',
    'paris saint germain': 'Paris Saint Germain',
}

CANONICAL_NATIONALITIES = {
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
    "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahrain",
    "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda",
    "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "British Virgin Islands",
    "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada",
    "Cape Verde", "Caribbean Netherlands", "Central African Republic", "Chad", "Chile", "China",
    "Colombia", "Comoros", "Cook Islands", "Costa Rica", "Croatia", "Cuba", "Curaçao",
    "Cyprus", "Czech Republic", "Denmark", "Dominican Republic", "DR Congo", "Ecuador",
    "Egypt", "El Salvador", "England", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia",
    "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "Gabon", "Gambia",
    "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Grenada", "Guadeloupe", "Guatemala",
    "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hong Kong", "Hungary",
    "Iceland", "India", "Indonesia", "Iran", "Iraq", "Israel", "Italy", "Ivory Coast",
    "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Korea DPR", "Kosovo", "Kuwait",
    "Kyrgyz Republic", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia",
    "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia", "Madagascar",
    "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Martinique", "Mauritania", "Mauritius",
    "Mexico", "Moldova", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique",
    "Namibia", "Nepal", "Netherlands", "New Caledonia", "New Zealand", "Nicaragua", "Niger",
    "Nigeria", "North & Central America", "Northern Ireland", "Norway", "Oman", "Pakistan",
    "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland",
    "Portugal", "Puerto Rico", "Qatar", "Republic of Ireland", "Republic of the Congo",
    "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia",
    "Saint Vincent and the Grenadines", "San Marino", "São Tomé and Príncipe", "Saudi Arabia",
    "Scotland", "Senegal", "Serbia", "Sierra Leone", "Singapore", "Sint Maarten", "Slovakia",
    "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South America", "South Korea",
    "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland",
    "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo", "Trinidad and Tobago",
    "Tunisia", "Turkmenistan", "Turkey", "Türkiye", "Uganda", "Ukraine", "United Arab Emirates",
    "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Wales",
    "Yemen", "Zambia", "Zimbabwe",
}

NATIONALITY_ALIASES = {
    "american": "United States", "usa": "United States", "us": "United States",
    "spanish": "Spain", "french": "France", "german": "Germany", "italian": "Italy",
    "english": "England", "british": "England", "welsh": "Wales", "scottish": "Scotland",
    "irish": "Republic of Ireland", "portuguese": "Portugal", "dutch": "Netherlands",
    "argentinian": "Argentina", "argentine": "Argentina", "brazilian": "Brazil",
    "uruguayan": "Uruguay", "turkey": "Türkiye", "turkiye": "Türkiye", "turkish": "Türkiye", "turk": "Türkiye",
    "moroccan": "Morocco", "nigerian": "Nigeria", "croatian": "Croatia",
    "polish": "Poland", "swedish": "Sweden", "norwegian": "Norway", "danish": "Denmark",
    "belgian": "Belgium", "austrian": "Austria", "swiss": "Switzerland",
    "mexican": "Mexico", "colombian": "Colombia", "chilean": "Chile", "paraguayan": "Paraguay",
    "peruvian": "Peru", "venezuelan": "Venezuela", "japanese": "Japan", "korean": "South Korea",
    "senegalese": "Senegal", "ghanaian": "Ghana", "cameroonian": "Cameroon",
    "egyptian": "Egypt", "algerian": "Algeria", "tunisian": "Tunisia",
    "ingiliz": "England", "brezilyali": "Brazil", "arjantinli": "Argentina",
    "norvecli": "Norway", "turkiye": "Türkiye", "türkiye": "Türkiye", "turk": "Türkiye", "alman": "Germany", "fransiz": "France",
    "ispanyol": "Spain", "italyan": "Italy", "portekizli": "Portugal", "hollandali": "Netherlands",
}

POSITION_NEGATION_ALIASES = {
    "goalkeeper": "Goalkeeper", "goal keeper": "Goalkeeper", "keeper": "Goalkeeper", "gk": "Goalkeeper",
    "kaleci": "Goalkeeper",
    "defender": "Center Back", "centre back": "Center Back", "center back": "Center Back", "cb": "Center Back",
    "stoper": "Center Back", "savunmaci": "Center Back",
    "midfielder": "Center Midfield", "central midfielder": "Center Midfield", "cm": "Center Midfield",
    "orta saha": "Center Midfield", "ortasaha": "Center Midfield",
    "winger": "Left Wing", "kanat": "Left Wing",
    "forward": "Center Forward", "striker": "Center Forward", "attacker": "Center Forward", "cf": "Center Forward",
    "forvet": "Center Forward", "santrafor": "Center Forward",
}
